apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets-provider
spec:
  provider: secrets-store.csi.k8s.io
  parameters:
    objects: |
      - objectName: "foodieFlow"
        objectType: "secretsmanager"
        objectAliases:  # Mapeamento das chaves do Secrets Manager para as variáveis de ambiente
          username: "DB_USER"
          password: "DB_PASSWORD"
          db_name: "DB_NAME"
          host: "DB_HOST"
          pool: "COGNITO_POOL_ID"
          client_id: "CLIENT_ID"